version: '3.8'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  backend:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis

  consumer-update-user-point:
    build: ./consumer-updateUserPoint
    ports:
      - '8001:8001'
    volumes:
      - ./consumer-updateUserPoint:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis
      
  consumer-update-item-count:
    build: ./consumer-updateItemCount
    ports:
      - '8002:8002'
    volumes:
      - ./consumer-updateItemCount:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis

  consumer-create-order:
    build: ./consumer-createOrder
    ports:
      - '8003:8003'
    volumes:
      - ./consumer-createOrder:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  redis_data:
  