apiVersion: v1
kind: Service
metadata:
  name: last-bite-create-order-consumer-service
spec:
  selector:
    app: last-bite-create-order-consumer
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-bite-create-order-consumer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: last-bite-create-order-consumer
  template:
    metadata:
      labels:
        app: last-bite-create-order-consumer
    spec:
      containers:
        - name: last-bite-create-order-consumer-api 
          image: whdgnszz1/last-bite-create-order-consumer:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: DATABASE_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: REDIS_HOST
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
