apiVersion: v1
kind: Service
metadata:
  name: last-bite-service
spec:
  selector:
    app: last-bite
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-bite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: last-bite
  template:
    metadata:
      labels:
        app: last-bite
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'  
    spec:
      containers:
        - name: last-bite-api
          image: whdgnszz1/last-bite-backend:latest
          readinessProbe:
            httpGet: 
              path: /
              port: 8000
          livenessProbe: 
            httpGet:
              path: /  
              port: 8000
            initialDelaySeconds: 15  
            timeoutSeconds: 3        
            periodSeconds: 10        
            failureThreshold: 3      
          resources:
            requests:
              memory: 700Mi
              cpu: 1000m
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: PORT
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: COOKIE_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: DATABASE_URL
            - name: ACCESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: ACCESS_SECRET_KEY
            - name: REFRESH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: REFRESH_SECRET_KEY
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: CLIENT_URL
            - name: AWS_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: AWS_S3_ACCESS_KEY
            - name: AWS_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: AWS_S3_SECRET_KEY
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: AWS_S3_REGION
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: AWS_S3_BUCKET_NAME
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: REDIS_HOST
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
