apiVersion: v1
kind: Service
metadata:
  name: last-bite-update-item-consumer-service
spec:
  selector:
    app: last-bite-update-item-consumer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-bite-update-item-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: last-bite-update-item-consumer
  template:
    metadata:
      labels:
        app: last-bite-update-item-consumer
    spec:
      containers:
        - name: last-bite-update-item-consumer-api 
          image: whdgnszz1/last-bite-update-item-consumer:latest
          readinessProbe:
            httpGet: 
              path: /main
              port: 8002
          livenessProbe: 
            httpGet:
              path: /main
              port: 8002
            initialDelaySeconds: 7
            timeoutSeconds: 3        
            periodSeconds: 10        
            failureThreshold: 3  
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: DATABASE_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: last-bite-secret
                  key: REDIS_HOST
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
